// Generated by https://quicktype.io

export interface AbstractEmailResponse {
  email:               string;
  autocorrect:         string;
  deliverability:      string;
  quality_score:       number;
  is_valid_format:     Is;
  is_free_email:       Is;
  is_disposable_email: Is;
  is_role_email:       Is;
  is_catchall_email:   Is;
  is_mx_found:         Is;
  is_smtp_valid:       Is;
}

export interface Is {
  value: boolean;
  text:  string;
}

// Generated by https://quicktype.io

export interface AbstractPhoneResponse {
  phone:    string;
  valid:    boolean;
  format:   Format;
  country:  Country;
  location: string;
  type:     string;
  carrier:  string;
}

export interface Country {
  code:   string;
  name:   string;
  prefix: string;
}

export interface Format {
  international: string;
  local:         string;
}
